### ISSUE TITLE
Conflicting redis shards name

### ISSUE THREAD

**Issue by rmarronnier** [cable-cr/cable#74]
I followed the installation instructions to add cable to a lucky project and got hit by a shards install issue : https://github.com/crystal-lang/shards/issues/590

```bash
Error shard name (redis) has ambiguous sources: 'git: https://github.com/jgaskins/redis.git' and 'git: https://github.com/stefanwille/crystal-redis.git'.
```

The readme installation part could be updated to : 
```yaml
  cable:
    github: cable-cr/cable
    branch: master
  redis:
    github: jgaskins/redis
    branch: master # lock down if needed
  ```
  Or a new release could be put out.
